#!/bin/bash
#SBATCH --gres=gpu:a100:1
#SBATCH --cpus-per-task=8
#SBATCH --time=48:00:00
#SBATCH --mem=100G
#SBATCH --mail-user=i.lin@mail.utoronto.ca
#SBATCH --mail-type=ALL
#
module load cuda
module load python/3.11
module load scipy-stack
source /home/noidvan/projects/def-hugh/noidvan/venvs/3dvista/bin/activate

cd /home/noidvan/projects/def-hugh/noidvan/3d_3D-VisTA
export WANDB_MODE=offline
export HF_HUB_OFFLINE=1
python3 run.py --config project/vista_reproduce/pretrain_3d.yml